### ISSUE TITLE
Nvidia Triton Inference supported?

### ISSUE THREAD

**Issue by vivekkalyanarangan30** [m87-labs/moondream#149]
@vikhyat is Nvidia triton inference supported or can you point me somewhere to make this work? I have been looking around and nothing looks like it will work out of the box. Amazing job on the model btw, cheers!

**Comment by vikhyat** [comment]
Not yet but we have ONNX exports (see `clients/python/README.md`) and I see that ONNX has support for a Triton backend... would that work for you?

**Comment by vivekkalyanarangan30** [comment]
@vikhyat this definitely is a starting point. I will try and take the time to test on triton as well as `onnxruntime-web`. That way I will be able to contribute to documentation as well, thanks for this!
