### ISSUE TITLE
Request for Model Usage and Citation in Research Paper

### ISSUE THREAD

**Issue by lt152** [m87-labs/moondream#150]
Hello, can I use this model in my own research paper, and how to cite it, thank you for your reply

**Comment by grndng** [comment]
On [huggingface](https://huggingface.co/vikhyatk/moondream2) there is a doi for this project where you can get information for citation:

```
@misc {vik_2024,
	author       = { {vik} },
	title        = { moondream2 (Revision 92d3d73) },
	year         = 2024,
	url          = { https://huggingface.co/vikhyatk/moondream2 },
	doi          = { 10.57967/hf/3219 },
	publisher    = { Hugging Face }
}
```

In any case I think I'd change the author to his proper name and might point the url to [moondream.ai](https://moondream.ai/) instead.

**Comment by vikhyat** [comment]
Thanks @grndng -- would something like this work?

@misc {vik_2024,
	author       = { {Vikhyat Korrapati} },
	title        = { moondream2 (Revision 92d3d73) },
	year         = 2024,
	url          = { https://moondream.ai/ },
	doi          = { 10.57967/hf/3219 }
}
