### ISSUE TITLE
Please add a license for the code in this repo

### ISSUE THREAD

**Issue by mbrukman** [m87-labs/moondream#23]
First, thank you for sharing this project with us!

I see the weights license is addressed in the README:

https://github.com/vikhyat/moondream/blob/9d678c9984f23ae045b911f0ae21ec533e22d10c/README.md?plain=1#L8

However there's no statement as to the license of the code of this repo.

Could you please add a license statement, and ideally a `LICENSE` file to the repo to clarify?

Per [GitHub docs on licensing][github-docs-licensing]:

> [...] without a license, the default copyright laws apply, meaning that you
> retain all rights to your source code and no one may reproduce, distribute,
> or create derivative works from your work. If you're creating an open source
> project, we strongly encourage you to include an open source license.

Thanks!

[github-docs-licensing]: https://help.github.com/articles/licensing-a-repository/#choosing-the-right-license

**Comment by kachiO** [comment]
yes please add a license

**Comment by vikhyat** [comment]
I'm training a new version of the model that will have an open license, will update the license in the repository to Apache 2.0 in a few days when it's out! Just worried about people getting confused if the code and model weights have different licenses.

**Comment by PaulFidika** [comment]
https://github.com/haotian-liu/LLaVA/commit/ba72f82cc610b01dc27764b483dfe982948b0633

LLaVA updated their license on their README on December 22nd, and, in my opinion, LLaVA now fully permits commercial usage. Previous iterations of their dataset had a non-commercial CC license imposed by the creators, but this revision removed that restriction.

Their remaining stipulations are around Llama 2's community license and OpenAI's terms of service.

**Comment by vikhyat** [comment]
Excellent news - though it looks like we're still limited by the OpenAI terms of use? Llama stipulation doesn't apply here since this is based on Phi-1.5.

**Comment by PaulFidika** [comment]
I don't know the details personally, but OpenAI has a stipulation in their TOS that GPT4 outputs should not be used to train competing models, and I think LLaVA used GPT4 to generate some of its dataset.

I'm not a lawyer, but I don't know how OpenAI can impose terms of use upon their models' outputs. AI-produced outputs cannot be copyrighted because copyright only applies to human-authored works. Hence, OpenAI does not own any of the outputs their models create.

And thanks for creating this model by the way! You're doing great work. I was just looking for an open-source GPT4-Vision alternative! It'll be very useful for content-moderation of images.

**Comment by vikhyat** [comment]
I think I'll swap out the LLaVA dataset regardless, don't want people to have to worry about taking on legal risk. Pretty sure I can do it without hurting performance.

> And thanks for creating this model by the way! You're doing great work. I was just looking for an open-source GPT4-Vision alternative! It'll be very useful for content-moderation of images.

Thank you very much!

**Comment by zubairahmed-ai** [comment]
@vikhyat Looking forward to an open license that allows commercial use

**Comment by fakerybakery** [comment]
> I'm training a new version of the model that will have an open license, will update the license in the repository to Apache 2.0 in a few days when it's out! Just worried about people getting confused if the code and model weights have different licenses.

Hi, is there any update on this or is the new version the one you posted on Twitter about that cost more to train then your house :)?

**Comment by vikhyat** [comment]
License is updated - Apache 2.0. Note that this applies to the code in this repository, and the moondream2 weights. moondream1 weights still have the old license.

Closing this issue, please reopen if I’ve missed mentioning the license anywhere!

**Comment by fakerybakery** [comment]
Thanks!
