### ISSUE TITLE
How to fine-tune it?

### ISSUE THREAD

**Issue by ryanshrott** [m87-labs/moondream#32]
Any fine-tuning example notebooks?

**Comment by vikhyat** [comment]
Just uploaded a notebook that shows how to fine-tune the model.

https://github.com/vikhyat/moondream/blob/main/notebooks/Finetuning.ipynb

Feel free to reopen if you run into any issues with the script!

**Comment by R3xpook** [comment]
would be possible to use peft ?

**Comment by faizan1041** [comment]
> Just uploaded a notebook that shows how to fine-tune the model.
> 
> https://github.com/vikhyat/moondream/blob/main/notebooks/Finetuning.ipynb
> 
> Feel free to reopen if you run into any issues with the script!

@vikhyat The dataset used in the notebook is the OCR one: https://huggingface.co/datasets/project-sloth/captcha-images   What if we want to fine-tune it for our image descriptions? Does that mean we have to format the dataset with the same structure? Image in one column and description in the 'solution' column?

**Comment by Spritan** [comment]
> Just uploaded a notebook that shows how to fine-tune the model.
> 
> https://github.com/vikhyat/moondream/blob/main/notebooks/Finetuning.ipynb
> 
> Feel free to reopen if you run into any issues with the script!

What type of respourse consumption can be expected while finetuning?

**Comment by hyderhafiz** [comment]
Anyone have an idea on how to inference for object detection using the finetuned model ?

**Comment by Junaidfayazlone** [comment]
@hyderhafiz, please check fine tune folder of the repository, he has already showed how to fine tune for object detection. have a good day mate.
