### ISSUE TITLE
running sample.py fails, quick fix was to pass tokenizer as third param

### ISSUE THREAD

**Issue by senthilnayagam** [m87-labs/moondream#39]
Hi,
running sample.py fails, quick fix was to pass tokenizer as third param
answer = moondream.answer_question(image_embeds, prompt,tokenizer)

https://github.com/vikhyat/moondream/blob/de750a63ec3546c6f2dccde2d90902f314ac1cf8/sample.py#L76

thanks
Senthil

**Comment by vikhyat** [comment]
fixed, ty! https://github.com/vikhyat/moondream/commit/0a847cba9d6a906f16866cef55abc3d08591d384
