### ISSUE TITLE
exclamation response !!!!!!!!

### ISSUE THREAD

**Issue by IceTea42** [m87-labs/moondream#48]
Thanks for this work, it was working great on my local machine until today. I don't know what I changed*, I only get a string of exclamation signs as response to any question that I ask. Any hints? 
\* conda env is the same. !!! happens regardless cpu or cuda, or the image resolution.
\* After some debugging I see that the image embedding has all nans

**Comment by JPGranizo** [comment]
I have the same problem using the ComfyUI implementation of this by kijai (https://github.com/kijai/ComfyUI-moondream).

The comfyUI implementation by Hangover3832 is still working, though (https://github.com/Hangover3832/ComfyUI-Hangover-Moondream).

![image](https://github.com/vikhyat/moondream/assets/57099674/56fba834-2558-4ddc-8fd6-f0d102eeedaa)

**Comment by vikhyat** [comment]
Could you try pulling the latest code? I had made an update to the projection layer architecture without updating the model version number a few weeks back, I suspect that might be what's causing this.

(Lesson learned though, won't happen again!)

**Comment by IceTea42** [comment]
Thanks for the replies. Normally I am up-to-date with the weight & code. It works by changing 
`moondream = Moondream.from_pretrained(model_id).to(device=device, dtype=dtype)`
to 
`
moondream = AutoModelForCausalLM.from_pretrained(model_id, force_download=True, trust_remote_code=True).to(
        device=device, dtype=dtype)
`
similar to the example given on the weights page.

**Comment by b67294** [comment]
i still feel confused about how this sloved...
