### ISSUE TITLE
Any response starting with "No" is is dropping the "N" 

### ISSUE THREAD

**Issue by dabeckham** [m87-labs/moondream#51]
While using gradio_demo.py,  I noticed that anytime time a response starts with "No" it seems to drop the first character. For example : "o, UPS does not offer pickup services for returns at home. The return summary card indicates that the UPS store is the location where the return should be made." 

When using sample.py, the response is complete. ""No, UPS does not offer..." 

Any Thoughts?

**Comment by vikhyat** [comment]
I've noticed the same, no clue what's causing it. :(

Seems like a new problem, it used to work before.

**Comment by vikhyat** [comment]
Hmm, I wonder if this line is causing it.

https://github.com/vikhyat/moondream/blob/main/gradio_demo.py#L47

**Comment by vikhyat** [comment]
Fixed here: https://github.com/vikhyat/moondream/commit/1f862763147d43e714579af7571312630f6e6fb9
