### ISSUE TITLE
How do we use video_gradio_demo.py ??

### ISSUE THREAD

**Issue by dabeckham** [m87-labs/moondream#52]
I've tried several times to use video_gradio_demo.py   

Each time, the server seems to launch but when I browse the page, processing is counting up, and the upload button never becomes available while an icon continues to spin in its place.

Not sure how to use it.

**Comment by vikhyat** [comment]
I renamed it to `webcam_gradio_demo.py` for clarity - that demo shows off real-time inference using your device's camera.
