### ISSUE TITLE
Does not understands questions

### ISSUE THREAD

**Issue by PierrunoYT** [m87-labs/moondream#55]
It does not understand questions like where is this image taken or what meal is this

**Comment by vikhyat** [comment]
Was able to reproduce, thanks! I have a pretty good idea what's causing this, should have it fixed in a few days.

<img width="739" alt="Screenshot 2024-03-05 at 3 10 19 PM" src="https://github.com/vikhyat/moondream/assets/31063/64d8a45a-97f8-498e-950c-ddd0f971f413">

**Comment by PierrunoYT** [comment]
Awesome thx you :)

**Comment by vikhyat** [comment]
Should be fixed by today's release! Going to close this, please feel free to reopen or open a new issue if you find any other issues!

<img width="730" alt="Screenshot 2024-03-06 at 8 48 22 PM" src="https://github.com/vikhyat/moondream/assets/31063/af528830-c3b8-47ef-bffe-5b31052e3783">
