### ISSUE TITLE
Finetuning

### ISSUE THREAD

**Issue by fakerybakery** [m87-labs/moondream#57]
Hi, is finetuning possible? Thanks!

**Comment by lforet** [comment]
Yes please release training scripts/doc when you can. I would be happy contribute ($) if necessary.

**Comment by vikhyat** [comment]
Just uploaded a notebook that shows how to fine-tune the model.

https://github.com/vikhyat/moondream/blob/main/notebooks/Finetuning.ipynb

Feel free to reopen if you run into any issues with the script!

**Comment by R3xpook** [comment]
> Just uploaded a notebook that shows how to fine-tune the model.
> 
> https://github.com/vikhyat/moondream/blob/main/notebooks/Finetuning.ipynb
> 
> Feel free to reopen if you run into any issues with the script!

maybeee peft can work too ?
