### ISSUE TITLE
Dataset Info

### ISSUE THREAD

**Issue by vishhvak** [m87-labs/moondream#61]
Hi @vikhyat, any chance you could shed some info on what datasets were used to train moondream2? Would appreciate the information to help adopting this commercially without any issues :)

**Comment by vedank07** [comment]
Not completely sure but it uses Llava dataset with some synthetic data. Could be wrong here

**Comment by vikhyat** [comment]
Hey - not planning to release details about the dataset at this time. If your company needs this information to be able to deploy it please reach out to contact@moondream.ai and we can discuss setting up some sort of contract with an NDA in place.
