### ISSUE TITLE
Availability On Ollama

### ISSUE THREAD

**Issue by jeffreylm** [m87-labs/moondream#62]
Dear Team,

Is there anyway we could see this model availanle via Ollama?

Thank you in advance,
Jeffrey

**Comment by vedank07** [comment]
I think when the gguf format is ready

**Comment by jeffreylm** [comment]
Thank you for the response.

**Comment by KPCOFGS** [comment]
@jeffreylm Apparently somebody has made gguf format of this model, I have never tested it. If you want to give it a try, here is the link: https://huggingface.co/sroecker/moondream2-GGUF/tree/main

**Comment by nicorinn** [comment]
How should the Modelfile be set up to work with ollama?

**Comment by vikhyat** [comment]
It is available now! You may need to use the latest pre-release version of ollama. https://ollama.com/library/moondream
