### ISSUE TITLE
Compare image embedding and text embedding 

### ISSUE THREAD

**Issue by Sangeeth-versos** [m87-labs/moondream#66]
Is there a way to compare the embedding of the image to embedding of the text and calculate similarity score?

**Comment by vikhyat** [comment]
This isn't supported by moondream - I'd recommend a model like [siglip-so400m-patch14-384](https://huggingface.co/google/siglip-so400m-patch14-384) for this purpose.

**Comment by hyperparameters** [comment]
as moondream uses siglip internally, is there a way I can do both tasks using the same model.

embedding of the text and calculating the similarity score,  as well as the other capabilities of moondream
