### ISSUE TITLE
Memory requirements

### ISSUE THREAD

**Issue by avsthiago** [m87-labs/moondream#7]
Hi,

I'm trying to run this model in a Google Colab but it is not working due to an OOM issue. Do you know how much memory is required to run this model?

I'm trying to run the following notebook:
[https://colab.research.google.com/drive/1kghOrIzykPePCUeeZQyo9r5pxfx3V3lo?usp=sharing](https://colab.research.google.com/drive/1kghOrIzykPePCUeeZQyo9r5pxfx3V3lo?usp=sharing)

**Comment by vikhyat** [comment]
Takes about 7GB running on my laptop, will check out what’s going on with colab when I get a chance

**Comment by avsthiago** [comment]
Thanks, @vikhyat. I managed to run the notebook using a GPU instance. 

The image below shows how much resources it uses from the notebook once the model is loaded.
<img width="387" alt="Screenshot 2024-01-22 at 21 45 57" src="https://github.com/vikhyat/moondream/assets/13870565/707b3af2-b1cb-42d2-9572-7ec78f0c9091">

The same link for the notebook should have the final version.
[https://colab.research.google.com/drive/1kghOrIzykPePCUeeZQyo9r5pxfx3V3lo?usp=sharing](https://colab.research.google.com/drive/1kghOrIzykPePCUeeZQyo9r5pxfx3V3lo?usp=sharing)
