### ISSUE TITLE
Request: Parameterize Prompt?

### ISSUE THREAD

**Issue by ghost** [m87-labs/moondream#77]
Hi!

Thanks for your amazing efforts with moondream. It's lovely! 
I was poking around and noticed that the prompt templates are hard-coded in:

- https://github.com/vikhyat/moondream/blob/b944eb475082f803b0f3a5ab4074567dea7f2561/moondream/moondream.py#L120
-  https://github.com/vikhyat/moondream/blob/b944eb475082f803b0f3a5ab4074567dea7f2561/moondream/moondream.py#L94

Would you be open to making this template a parameter for the `answer_question` and `batch_answer` methods?

Otherwise users will have to invoke `generate` directly, but there's a good bit of boiler plate to copy: https://github.com/vikhyat/moondream/blob/b944eb475082f803b0f3a5ab4074567dea7f2561/moondream/moondream.py#L122-L169

What are your thoughts on this?

**Comment by vikhyat** [comment]
The model is only trained on that prompt format so I'm not sure anything else will work well. What type of prompt are you trying out?

**Comment by ghost** [comment]
After looking more closely at this I realized that the format is baked in as part of training. I was just wondering if it would pose any issues, but from my experimentation this is perfectly sufficient. Thanks again, this is my favorite multimodal model by far! I am experimenting with fine-tuning on my own data.
