### ISSUE TITLE
Regarding the foundation model

### ISSUE THREAD

**Issue by lingyezhixing** [m87-labs/moondream#81]
Why not adopt Phi-2 as the foundation model for this visual dialogue system, considering its potential and effectiveness?

**Comment by vikhyat** [comment]
Sub-2B parameters is a bit of a sweet spot for running on some of the target devices we have in mind. Currently focusing our effort on improving model accuracy at the current size, but definitely considering offering larger variants in the future.

**Comment by R3xpook** [comment]
tiny llama is good at least good to fine tuning , don't know if it applies well for VLM too , tho think phi models are more solid than tiny llama
