### ISSUE TITLE
Has anyone exported ONNX model?

### ISSUE THREAD

**Issue by jamjamjon** [m87-labs/moondream#88]

**Comment by xenova** [comment]
I've made one here: https://huggingface.co/Xenova/moondream2. It contains three submodules (across different quantizations):
- vision encoder + multimodal projection layer (vision_encoder.onnx)
- embedding layer (embed_tokens.onnx)
- text model (decoder_model_merged.onnx)

**Comment by jamjamjon** [comment]
cool! Thanks! @xenova

**Comment by Tsardoz** [comment]
@xenova I followed the example here https://huggingface.co/Xenova/moondream2 but when I try and run the script I am getting:

> node index.mjs
file:///home/tsardoz/moondreamONNX/index.mjs:1
import { AutoProcessor, AutoTokenizer, Moondream1ForConditionalGeneration, RawImage } from '@xenova/transformers';
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module '@xenova/transformers' does not provide an export named 'Moondream1ForConditionalGeneration'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12)
Node.js v18.20.3
>

**Comment by Tsardoz** [comment]
Please ignore my last comment. This is being discussed here:

https://huggingface.co/Xenova/moondream2/discussions/7
