### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [m87-labs/moondream#9]
Hi,
What's the license for Moondream?
Thanks!

**Comment by vikhyat** [comment]
Would be CC-BY 4.0 since it was trained on the LLaVA dataset, will update the readme shortly.

**Comment by fakerybakery** [comment]
OK, thanks!x

**Comment by vikhyat** [comment]
Updated the README, but also working on a new version of the model that will allow commercial use. Stay tuned!

**Comment by fakerybakery** [comment]
Hi, what is the license for the code? Is it Apache since it's now integrated into HF Transformers?
